#!/bin/bash

check_exit_status() {
    if [ $? -eq 0 ]
    then
        echo
        echo "Success"
        echo
    else
        echo
        echo "[Error] Process failed!"
        echo

        read -p "The last command existed with an error. Exit script? (yes/no)" answer

        if [ "$answer" == "yes" ]
        then
            exit 1
        fi
    fi
}

greeting(){
    echo
    echo "Hello, $USER. Let's update this system."
    echo

}

update() {
    sudo apt update;
    check_exit_status

    sudo apt full-upgrade -y;
    check_exit_status

}

housekeeping() {
    sudo apt autoremove -y;
    check_exit_status

    sudo apt autoclean -y;
    check_exit_status

    sudo updatedb;
    check_exit_status
}

leave() {
    echo "--------------------"
    echo "- Update Complete! -"
    echo "--------------------"
    exit
}

greeting
update
housekeeping
leave
